[package]
name = "fecs"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
fecs-macros = { path = "./macros" }
legion = { git = "https://github.com/TomGillen/legion", rev = "c5b9628630d4f9fc54b6843b5ce02d0669434a61", default-features = false, features = ["par-iter"] }
fxhash = "0.2"
inventory = "0.1"

[workspace]
members = [".", "macros"]
